name: Flask CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Verify Flask App
        run: python -m py_compile app.py



      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image
        run: |
          docker build -t flask-app .

      - name: Tag Image
        run: |
          docker tag flask-app:latest \
          997241706047.dkr.ecr.ap-south-1.amazonaws.com/ci-cd-test-repo:latest

      - name: Push Image to ECR
        run: |
          docker push \
          997241706047.dkr.ecr.ap-south-1.amazonaws.com/ci-cd-test-repo:latest




      - name: Deploy to ECS
        run: |
          aws ecs update-service \
            --cluster ci-cd-test-cluster \
            --service ci-cd-task-service-m6fxxnqj \
            --force-new-deployment